auth/jwtToken.go, login/db/query.sql, login/db/query.sql.go, login/login.gen.go, login/login.go, login/login.yaml, login/route.go, utils/utils.go
```
"CustomClaims": {
"user_uuid": "ee8f755f-5427-4150-9af0-12674a1108b3",
"role": [
"Admin",
"User"
]
},
```
```
{
"message": "Login successful",
"status": "success",
"user": {
"email": "test@gmail.com",
"name": "testname",
"uuid": "ee8f755f-5427-4150-9af0-12674a1108b3"
}
}
```
```
> POST http://localhost:4444/api/v4/login
> content-type: application/json
> data {"username":"testuser","password":"password"}
< 200 OK
< content-type: application/json; charset=utf-8
< set-cookie: accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDdXN0b21DbGFpbXMiOnsidXNlcl91dWlkIjoiZWU4Zjc1NWYtNTQyNy00MTUwLTlhZjAtMTI2NzRhMTEwOGIzIiwicm9sZSI6WyJBZG1pbiIsIlVzZXIiXX0sImlzcyI6InNpbXBsZS1pZG0iLCJzdWIiOiJzaW1wbGUtaWRtIiwiYXVkIjpbInB1YmxpYyJdLCJleHAiOjE3MjkxOTU0NjUsIm5iZiI6MTcyOTE5NDg2NSwiaWF0IjoxNzI5MTk1MTY1LCJ …
```
=> Zsh update idm 1

auth/jwtToken.go
=> fix: sig base64 encode

auth/jwtToken.go, pkg/login/handle.go, pkg/login/login.gen.go, pkg/login/login.yaml
Bruno Test
```
> POST http://localhost:4444/logout
> content-type: application/json
> data {"username":"admin","password":"pwd"}
< 200 OK
< cache-control: no-cache, no-store, no-transform, must-revalidate, private, max-age=0
< expires: Thu, 01 Jan 1970 00:00:00 GMT
< pragma: no-cache
< set-cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21fY2xhaW1zIjp7ImN1c3RvbV9jbGFpbXMiOm51bGx9LCJpc3MiOiJzaW1wbGUtaWRtIiwic3ViIjoic2ltcGxlLWlkbSIsImF1ZCI6WyJwdWJsaWMiXSwiZXhwIjoxNzI5NTM5Mzg0LCJuYmYiOjE3Mjk1MzkxNDQsImlhdCI6MTcyOTUzOTQ0NCwianRpIjoiZDcyNDVhOTgtMzU3MS00MjY3LWJkMTQtZjIyMDFmMDJhZTQ4In0.uFy+ok585/keJc/SreQ06hFOEqFEPHSD9DoKwApJaUM=; Path=/; Expires=Mon, 21 Oct 2024 19:36:24 GMT; HttpOnly; Secure; SameSite=LaxrefreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21fY2xhaW1zIjp …
```
=> Zsh logout api

pkg/auth/handle.go, pkg/login/sservice_test.go
Return 400 if password hash check failed.
=> fix: return 400 if check hash password error

README.md
This PR provides a comprehensive improvement to the README documentation:
- Added proper H1 title and project description
- Organized content into clear, hierarchical sections
- Improved overall document flow and readability
- Added "Getting Started" section with build and run instructions
- Added version requirements for Go (1.21+) and PostgreSQL (14+)
- Added clear documentation about default port (4000)
- Added explicit documentation about default user credentials
- Added language annotations to code blocks (sql, bash)
- Converted TODO list into a structured Roadmap with checkboxes
- Simplified and clarified SQL examples
- Improved API testing section with better formatted curl commands
- Fixed typos and formatting inconsistencies
- Improved curl examples with proper line breaks and …
=> Comprehensive README improvements

cmd/login/main.go, pkg/login/handle.go, pkg/login/login.gen.go, pkg/login/login.yaml, pkg/login/options.go, pkg/login/service.go, pkg/twofa/handle.go, pkg/twofa/service.go, pkg/twofa/service_test.go, pkg/twofa/twofa.gen.go, pkg/twofa/twofa.yaml
=> Update login flow with login level 2FA

cmd/login/main.go, frontend/src/App.tsx, frontend/src/api/client.ts, frontend/src/api/twoFactor.ts, frontend/src/api/user.ts, frontend/src/pages/Login.tsx, frontend/src/pages/TwoFactorVerification.tsx, pkg/login/handle.go, pkg/login/login.gen.go, pkg/login/login.yaml, pkg/twofa/handle.go, pkg/twofa/service.go, pkg/twofa/service_test.go, pkg/twofa/twofa.gen.go, pkg/twofa/twofa.yaml
- use hashed email instead of plaintext
- refactor the access and refresh token set during login with 2fa enabled
=> 2fa: Complete the login flow with 2fa enabled

frontend/src/api/twoFactor.ts, frontend/src/api/user.ts, frontend/src/pages/Login.tsx, frontend/src/pages/TwoFactorVerification.tsx, pkg/login/handle.go, pkg/login/login.gen.go, pkg/login/login.yaml, pkg/login/mapper.go, pkg/login/service.go, pkg/twofa/handle.go, pkg/twofa/service.go, pkg/twofa/service_test.go, pkg/twofa/twofadb/models.go, pkg/twofa/twofadb/query.sql, pkg/twofa/twofadb/query.sql.go, pkg/utils/utils.go
Sample response from POST /auth/login API
```{
"message": "2FA verification required",
"status": "2fa_required",
"temp_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21fY2xhaW1zIjp7InVzZXJfaWQiOiI3ZjFlNWIwZS03MWRhLTQxYzEtYTVjNS01MjlhNTQ4MTQ5MDciLCJsb2dpbl9pZCI6ImQzMTVmMjQwLWNjZDEtNGFmZC1iNmU2LWI1ZmJhNjA4NGY3NCIsImVtYWlsIjoiYWRtaW4yMjhAZXhhbXBsZS5jb20iLCJkaXNwbGF5X25hbWUiOiJhZG1pbjIyOCIsImV4dHJhX2NsYWltcyI6eyJlbWFpbCI6ImFkbWluMjI4QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwidXNlcm5hbWUiOiJhZG1pbjIyOCJ9fSwiaXNzIjoic2ltcGxlLWlkbSIsInN1YiI6InNpbXBsZS1pZG0iLCJhdWQiOlsiMmZhIl0sImV4cCI6MTc0MTAzMzk1NywibmJmIjoxNzQxMDMzNjU3LCJpYXQiOjE3NDEwMzM2NTcsImp0aSI6Ijg0NGE2YmE5LWZjYjUtNDJmNS04MTIyLTY1OWI4MWM4YzM0OSJ9.XZJzxpWYL4HBcICztZDCYqPdBxz_xd6MF0bNvSFE_Eg",
"two_factor_methods": [
{ …
```
=> Feat: 2fa support hashed email value

pkg/login/passwordmanager.go, pkg/login/policychecker.go, pkg/login/service.go
=> FEAT: remove extra methods in policychecker interface, return multiple error for password validation

cmd/login/main.go, frontend/src/api/twoFactor.ts, frontend/src/api/user.ts, frontend/src/pages/Login.tsx, frontend/src/pages/TwoFactorVerification.tsx, pkg/login/handle.go, pkg/login/login.gen.go, pkg/login/login.yaml, pkg/login/service.go, pkg/twofa/handle.go, pkg/twofa/twofa.gen.go, pkg/twofa/twofa.yaml
sample response of POST /2fa/validate with multiple users
```
{
"message": "Multiple users found, please select one",
"status": "select_user_required",
"temp_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21fY2xhaW1zIjp7ImRpc3BsYXlfbmFtZSI6ImFkbWluMjI4IiwiZW1haWwiOiJhZG1pbjIyOEBleGFtcGxlLmNvbSIsImV4dHJhX2NsYWltcyI6eyJlbWFpbCI6ImFkbWluMjI4QGV4YW1wbGUuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwidXNlcm5hbWUiOiIifSwibG9naW5faWQiOiJkMzE1ZjI0MC1jY2QxLTRhZmQtYjZlNi1iNWZiYTYwODRmNzQiLCJ1c2VyX2lkIjoiN2YxZTViMGUtNzFkYS00MWMxLWE1YzUtNTI5YTU0ODE0OTA3In0sImlzcyI6InNpbXBsZS1pZG0iLCJzdWIiOiJzaW1wbGUtaWRtIiwiYXVkIjpbIjJmYSJdLCJleHAiOjE3NDExMjIzNTYsIm5iZiI6MTc0MTEyMjA1NiwiaWF0IjoxNzQxMTIyMDU2LCJqdGkiOiIwM2RkY2M4MS0zZjllLTRlMjAtOWE4My00NTcyN2ZhNWU5OGMifQ.UZTSviNWSiQIULxgwVgnhHHlwVBWJySdl__6PVYNUvg",
"users": [ …
```
=> Switch User: support selecting user after login/2fa validation passed

cmd/login/main.go, frontend/src/api/twoFactor.ts, frontend/src/pages/Logins.tsx, frontend/src/pages/Settings.tsx, pkg/login/client.go, pkg/profile/handle.go, pkg/profile/profile.gen.go, pkg/profile/profile.yaml, pkg/twofa/service.go, pkg/twofa/twofadb/query.sql, pkg/twofa/twofadb/query.sql.go
=> 2fa: support 2fa on user settings page

pkg/iam/api/handle.go, pkg/iam/service.go, pkg/login/params.go, pkg/login/passwordmanager.go, pkg/login/repository.go, pkg/login/service.go, pkg/profile/api/handle.go, pkg/profile/service.go
- fix iam nil pointer error
- remove getLogInByUserId in login repository
- for change password, use loginid instead of userid
=> FIX: iam nil pointer error, login repo and change password 

pkg/login/api/handle.go, pkg/login/api/login.gen.go, pkg/login/api/login.yaml, pkg/mapper/mapper.go
- Add GET api to get all users associated with login id
- Add more fields in MappedUser struct
=> Switch users: Add GET api to get all users associated with login id

frontend/src/api/twoFactor.ts, frontend/src/api/user.ts, frontend/src/pages/TwoFactorVerification.tsx, pkg/twofa/api/handle.go
- Update 2fa get login id from AuthUser
- Update frontend based on api update
=> 2fa: Update 2fa get login id from AuthUser

pkg/login/api/handle.go, pkg/token/token.go, pkg/twofa/api/handle.go
Reverts tendant/simple-idm#114
=> Revert "FEAT: update tokenservice interface method to pass in cookie name"

pkg/login/api/handle.go
This PR will provide a solution for following issue. Local integration test passed in app-idm.
=> Refactor PrepareUserSelectionResponse

frontend/src/api/twoFactor.ts, frontend/src/pages/Login.tsx, frontend/src/pages/TwoFactorVerification.tsx, pkg/login/api/handle.go, pkg/login/api/login.gen.go, pkg/login/api/login.yaml
**Openhand review:**
Let me analyze the changes in this PR. The PR adds mobile-related APIs and makes some improvements to the existing code. Here's a detailed review:
1. API Changes:
- Added new mobile endpoints:
- `/mobile/2fa/send`: For send 2FA passcodes on mobile
- `/mobile/2fa/validate`: For validating 2FA passcodes on mobile
- `/mobile/user/switch`: For switching between multiple users when available
2. Frontend Changes:
- Updated status terminology from `select_user_required` to `multiple_users` for consistency
- Modified frontend components (Login.tsx and TwoFactorVerification.tsx) to handle the new status
- Updated API client code to support the new mobile endpoints
3. Backend Changes:
- Refactored login API to extract 2FA and multiple user handling into reusable methods
- Added …
=> FEAT: finish mobile related APIs

cmd/login/main.go, pkg/login/service.go, pkg/profile/api/handle.go, pkg/profile/api/profile.gen.go, pkg/profile/api/profile.yaml, pkg/profile/profiledb/models.go, pkg/profile/profiledb/query.sql, pkg/profile/profiledb/query.sql.go, pkg/profile/service.go, pkg/utils/utils.go
This PR implements a new feature to associate a login with the current user. Here's a detailed review:
The PR adds an API endpoint `/login/associate` that allows associating an existing login (username/password) with the current authenticated user.
1. **New API Endpoint**
- Added new POST endpoint `/login/associate` in `profile.yaml`
- Request body requires username and password
- Returns success response on successful association
2. **Profile Service Changes**
- Added `UpdateLoginId` method to update a user's login ID
- Changed dependency from `LoginService` to `PasswordManager` for better separation of concerns
- Added new `UpdateLoginIdParam` struct type
3. **Database Changes**
- Added new SQL query `UpdateUserLoginId` to update user's login_id
- Returns the updated login_id for …
=> FEAT: implement Associate Login with current user API

pkg/profile/api/handle.go, pkg/profile/api/profile.gen.go, pkg/profile/api/profile.yaml, pkg/profile/profiledb/query.sql, pkg/profile/profiledb/query.sql.go, pkg/profile/service.go
After reviewing the pull request #141 titled "FEAT: associate login flow", here's my analysis:
The PR implements a more robust login association flow with support for 2FA and login selection. Here are the key changes:
1. Enhanced Login Association Flow:
- Added support for 2FA verification during login association
- Added support for login selection when multiple logins are available
- Split the association flow into two steps when needed
2. New API Endpoints:
- Modified `/login/associate` to handle 2FA and login selection scenarios
- Added `/login/associate/complete` endpoint to finalize login selection
3. New Response Types:
- `LoginSelectionRequiredResponse`: When user needs to choose between logins
- `TwoFactorRequiredResponse`: When 2FA verification is required
- `LoginOption`: …
=> FEAT: associate login flow

frontend/src/pages/Settings.tsx, pkg/common/twofactor.go, pkg/login/api/handle.go, pkg/login/api/login.gen.go, pkg/login/api/login.yaml, pkg/login/passwordmanager.go, pkg/profile/api/handle.go, pkg/profile/api/profile.gen.go, pkg/profile/api/profile.yaml, pkg/tokengenerator/tokengenerator.go
Here's my analysis of PR #142 without code snippets:
1. Key Changes:
a. Common Package Creation:
- Added new `pkg/common/twofactor.go` to share 2FA functionality
- Moved common types and helper functions from login and profile packages
- Introduced reusable `Check2FAEnabled` function
b. Code Refactoring:
- Removed duplicate 2FA checking code from both packages
- Standardized response types and structures
- Improved token handling with login options support
2. Specific Improvements:
a. Common Types:
- Added shared DeliveryOption structure
- Added shared TwoFactorMethod structure
- Consistent type definitions across packages
b. Shared Helper Function:
- Centralized 2FA checking logic
- Consistent parameter handling
- Flexible support for web and non-web flows
c. Token Generator Enhancement: …
=> FEAT: finish Associate Login Flow

cmd/login/main.go, pkg/login/passwordmanager.go, pkg/login/service.go, pkg/profile/api/handle.go
Let me analyze the changes in this pull request:
1. Main Changes:
- Added a new `PostPasswordUpdateFunc` type and functionality to the login service
- Refactored the login service initialization to use a more flexible options pattern
- Added new `WithXXX` option functions for configuring the login service
2. Specific Changes:
a) In `pkg/login/service.go`:
- Added `PostPasswordUpdateFunc` type and field to `LoginService` struct
- Added new option functions:
- `WithNotificationManager`
- `WithUserMapper`
- `WithDelegatedUserMapper`
- `WithPasswordManager`
- `WithPostPasswordUpdate`
- Added `NewLoginServiceWithOptions` function that uses the functional options pattern
- Added `UpdatePassword` method that executes the post-password update function if provided
b) In `cmd/login/main.go`:
- …
=> FEAT: add PostPasswordUpdateFunc to loginService, refactor login service to add NewLoginServiceWithOptions

cmd/login/main.go, pkg/impersonate/api/handler.go, pkg/impersonate/repository.go, pkg/impersonate/service.go
After reviewing the PR changes, here's my analysis of the changes and improvements made:
1. **Architecture Improvements**:
- Replaced direct JWT service usage with more abstracted `TokenService` and `TokenCookieService` interfaces
- Removed duplicate token cookie handling code by using a dedicated service
- Better separation of concerns between token generation and cookie management
2. **Impersonation Flow Improvements**:
- Added proper token validation and claims checking for impersonation
- Improved handling of original user information in token claims
- Better error handling and validation throughout the flow
3. **Code Structure**:
- Removed redundant structs and simplified user mapping
- Added helper method `ToTokenClaims` to the service layer
- Better error messages and logging
1. …
=> FEAT: use token service and cookie service to generate token for impersonate

pkg/common/jwt.go, pkg/common/twofactor.go, pkg/login/api/handle.go, pkg/login/api/login.gen.go, pkg/login/api/login.yaml, pkg/profile/api/handle.go, pkg/profile/api/profile.gen.go, pkg/profile/api/profile.yaml, pkg/tokengenerator/tokengenerator.go
Let me analyze the changes in this PR and provide a comprehensive review. The PR implements an associate login feature with several key changes:
1. Code Organization and Refactoring:
- Moved common JWT claim extraction methods to `pkg/common/jwt.go`
- Consolidated token-related functionality
- Improved error handling and comments
- Renamed structures from "associate login" to "associate user" for better clarity
2. New Features:
- Implemented user association selection functionality
- Added 2FA verification tracking in claims
- Added support for associating users with logins
- Added new API endpoints for user association
3. Key Changes:
a) JWT Claims Handling:
- Added new methods in `pkg/common/jwt.go`:
- `GetLoginIDFromClaims`
- `GetUserIDFromClaims`
- `Get2FAVerifiedFromClaims`
- …
=> FEAT: implement associate login feature

pkg/login/api/handle.go, pkg/profile/api/handle.go
Let me analyze the changes in this pull request. The PR makes several important changes to improve the user experience and security in the simple-idm system:
1. Main Changes:
- Improves user flow when there's only one user with a login by skipping the user selection step
- Adds 2FA validation check in the mobile user switch API
- Fixes response body formatting and error handling
2. Specific Changes:
a) In `pkg/login/api/handle.go`:
- Added 2FA verification check for mobile user switch API
- Added proper error handling for 2FA verification
- Added validation for temp tokens and access tokens
b) In `pkg/profile/api/handle.go`:
- Modified user association logic to skip selection when there's only one user
- Improved error handling and logging
- Simplified code structure by removing redundant …
=> FIX: if only one user with the login, do not ask user to choose

pkg/login/service.go, pkg/mapper/mapperdb/query.sql, pkg/mapper/mapperdb/query.sql.go, pkg/mapper/usermapper.go, pkg/profile/api/handle.go, pkg/profile/api/profile.gen.go, pkg/profile/api/profile.yaml, pkg/profile/profiledb/query.sql, pkg/profile/profiledb/query.sql.go, pkg/profile/service.go
Here's the PR review without code blocks:
This PR implements two main features:
1. FindUsernamesByEmail functionality
2. Update username functionality
The changes add a new query to find usernames associated with an email address:
- Added SQL query to find usernames by email with proper JOIN
- Implemented the functionality in usermapper to handle query results
- Added logging for better observability
The changes add functionality to update a user's username:
- Modified SQL query to use updated_at instead of last_modified_at
- Added API endpoint with validation:
- Changed to use snake_case for consistency
- Implemented handler with proper error handling:
- Validates request body
- Checks for empty username
- Returns appropriate HTTP status codes for different scenarios
- 409 for username …
=> FEAT: implement FindUsernamesByEmail and update username

pkg/delegate/api/handler.go, pkg/delegate/repository.go, pkg/delegate/service.go, pkg/login/api/handle.go, pkg/mapper/usermapper.go, pkg/tokengenerator/tokengenerator.go
Here's the PR review without code blocks:
PR #163 - "FEAT: keep delegate_user_id and impersonate_user_id when refresh token"
This PR addresses an important functionality in the token refresh process, ensuring that delegation and impersonation contexts are maintained. Here's the key points:
1. Purpose:
- Preserves delegation and impersonation information during token refresh operations
- Prevents loss of user context when tokens are refreshed
- Maintains continuity of delegation and impersonation features
2. Main Changes:
- Enhances the token refresh handler to capture and preserve delegation/impersonation IDs
- Adds two new helper functions to extract user IDs from token claims
- Modifies token generation to include preserved IDs in new tokens
3. Implementation Details:
- Now captures the …
=> FEAT: keep delegate_user_id and impersonate_user_id when refresh token

pkg/notice/templates/email/password_reset.html
=> feat: Replace hardcoded username with template variable in password reset email template

pkg/common/twofactor.go, pkg/device/fingerprint.go, pkg/device/inmem_repository.go, pkg/device/inmem_repository_test.go, pkg/device/repository.go, pkg/device/service.go, pkg/device/service_test.go
Let me analyze the changes in this pull request. The PR makes several significant changes to the device recognition functionality in the simple-idm project:
1. Device Data Structure Refinements:
- Updated the `Device` struct to include additional fields:
- `AcceptHeaders` (sql.NullString)
- `Timezone` (sql.NullString)
- `ScreenResolution` (sql.NullString)
- Changed `DeletedAt` in `LoginDevice` struct to use `sql.NullTime` instead of `time.Time`
2. Fingerprint Data Collection:
- Now extracts timezone and screen resolution from request headers
- Modified `ExtractFingerprintDataFromRequest` to get these values from headers:
- `Timezone` from "Timezone" header
- `ScreenResolution` from "Screen-Resolution" header
3. Repository Interface Updates:
- Updated the in-memory repository …
=> FEAT: refine repository interface and struct, refine service methods, add tests

migrations/idm/20250430171100_create_login_attempts_table.sql, migrations/idm_db.sql, pkg/login/api/adapter.go, pkg/login/api/handle.go, pkg/login/api/login.gen.go, pkg/login/api/login.yaml, pkg/login/logindb/models.go, pkg/login/logindb/query.sql, pkg/login/logindb/query.sql.go, pkg/login/repository.go, pkg/login/service.go, pkg/login/sqlc.yaml
Here's the review without code blocks:
PR Review: FEAT: implement login_attempt record and account lock
Overview:
The PR implements login attempt tracking and account lockout functionality, enhancing the security of the authentication system.
Key Changes:
1. Database Changes:
- Added new login_attempts table to track authentication attempts
- Includes fields for tracking IP, user agent, device fingerprint
- Proper indexing and constraints for performance
- UTC timestamp tracking for all events
2. Login Service Enhancements:
- Configurable failed login attempt threshold (default: 5)
- Configurable lockout duration (default: 30 minutes)
- Standardized failure reason tracking
- Enhanced login result structure with detailed status information
3. Account Lockout Implementation:
- Progressive …
=> FEAT: implement login_attempt record and account lock

cmd/inituser/main.go, cmd/login/main.go, frontend/src/pages/Settings.tsx, go.mod, go.sum, migrations/idm/20250430171100_create_login_attempt_table.sql, migrations/idm_db.sql, pkg/login/api/handle.go, pkg/login/logindb/query.sql, pkg/login/logindb/query.sql.go, pkg/login/passwordmanager.go, pkg/login/policychecker.go
=> FEAT: test password min/max age and account lock

cmd/login/main.go, pkg/device/inmem_repository.go, pkg/device/psql_repository.go, pkg/device/repository.go, pkg/device/service_test.go, pkg/login/api/adapter.go, pkg/login/api/handle.go, pkg/login/api/login.gen.go, pkg/login/api/login.yaml, pkg/twofa/service.go, pkg/twofa/service_test.go
Based on my review of PR #175, here are the key points and recommendations:
Key Changes:
1. Constructor Pattern Refactoring:
- Introduced options pattern for service constructors
- Added DeviceRepositoryOptions for configurable device expiration
- Refactored TwoFaService to use functional options pattern
2. Device Expiration Configuration:
- Added DEVICE_EXPIRATION_DAYS environment variable
- Moved from hardcoded 90 days to configurable duration
- Added proper duration parsing with fallback to default
3. Repository Improvements:
- Added GetExpiryDuration() method to repository interface
- Updated both PostgreSQL and in-memory implementations
- Better synchronization in in-memory repository
4. API Enhancements:
- Added new /device/expiration endpoint
- Better configuration handling in …
=> FEAT: refactor code to use option for all constructor

cmd/login/main.go, frontend/src/api/profile.ts, frontend/src/pages/Settings.tsx, pkg/profile/api/handle.go, pkg/profile/api/profile.gen.go, pkg/profile/api/profile.yaml
Based on my review of PR #176, here are the key points and recommendations:
Key Changes:
1. API Refactoring:
- Moved unlink device functionality from device package to profile package
- Added new /devices/unlink endpoint in profile API
- Simplified client-side device unlinking process
2. Frontend Changes:
- Updated device unlinking logic in Settings.tsx
- Added new unlinkDevice method in profile.ts API client
- Improved error handling and user feedback
3. Backend Improvements:
- Added UnlinkDeviceFromLogin handler in profile API
- Better error handling with specific error messages
- Proper authentication and validation checks
4. Configuration:
- Added ISO 8601 duration parsing for device expiration
- Better handling of duration configuration in main.go
- Added logging for configuration …
=> FEAT: put unlink device API in profile pkg

migrations/idm/20250507120500_update_device_columns.sql, migrations/idm_db.sql, pkg/device/fingerprint.go, pkg/device/inmem_repository.go, pkg/device/psql_repository.go, pkg/device/repository.go, pkg/login/logindb/models.go, pkg/login/logindb/query.sql, pkg/login/logindb/query.sql.go, pkg/login/passwordmanager.go, pkg/login/repository.go, pkg/login/service.go
Based on my review of PR #178, here are the key points and recommendations:
Key Changes:
1. Mobile Device Recognition:
- Added device_id field for mobile device identification
- Implemented hashing of device_id for mobile fingerprints
- Added mobile device detection in user agent
2. Database Changes:
- Added device_id column (UUID) to device table
- Made user_agent column nullable
- Added index on device_id for better performance
- Added migration script for schema changes
3. Repository Layer Updates:
- Updated CRUD operations to handle device_id
- Added proper UUID handling with pgtype
- Improved error handling and logging
- Updated queries to include device_id
4. Device Fingerprinting:
- Added mobile-specific fingerprint generation
- Improved device type detection
- Added better logging …
=> FEAT: for mobile device recognition, hash device_id as fingerprint

pkg/login/api/handle.go
=> FEAT: update error handling for inactive account

pkg/login/service.go
=> FEAT: add post hook func for login attempt and reset password fact event

cmd/login/main.go, frontend/src/App.tsx, frontend/src/api/login.ts, frontend/src/api/signup.ts, frontend/src/api/utils.ts, frontend/src/pages/Login.tsx, frontend/src/pages/MagicLinkLogin.tsx, frontend/src/pages/MagicLinkValidate.tsx, frontend/src/pages/PasswordlessSignup.tsx, pkg/login/api/handle.go, pkg/login/api/login.gen.go, pkg/login/api/login.yaml, pkg/login/repository.go, pkg/login/service.go, pkg/logins/errors.go, pkg/logins/service.go, pkg/notice/service.go, pkg/notice/templates/email/magic_link_login.html, pkg/signup/handle.go, pkg/signup/signup.gen.go, pkg/signup/signup.yaml
=> FEAT: signup-passwordless and magic link login; return password complexity error for regular signup, add api to get password policy

pkg/login/api/handle.go, pkg/login/service.go
=> FIX: display account lock out period dynamically

migrations/idm/20250707095500_add_magic_link_and_passwordless.sql, migrations/idm_db.sql, pkg/login/logindb/models.go, pkg/login/logindb/query.sql, pkg/login/logindb/query.sql.go, pkg/login/repository.go, pkg/login/service.go, pkg/login/service_test.go
@livefire2015 @apan09 
Let me analyze the pull request #204 which adds functionality to persist magic link tokens in the database. Here's a detailed review:
Key Changes:
1. Database Schema Changes:
- Added new table `login_magic_link_tokens` with fields:
- id (UUID)
- login_id (UUID, foreign key to login table)
- token (varchar)
- created_at (timestamp)
- expires_at (timestamp)
- used_at (timestamp, nullable)
- Added indexes for performance on token and login_id columns
- Added `is_passwordless` boolean column to login table
2. Repository Layer Changes:
- Replaced in-memory token storage with database persistence
- Modified `GenerateMagicLinkToken` to store tokens in the database
- Updated `ValidateMagicLinkToken` to check token validity from database
- Added `MarkMagicLinkTokenUsed` to …
=> FEAT: persist magic link token in db

cmd/login/main.go, pkg/login/repository.go, pkg/login/service.go, pkg/notice/templates/email/magic_link_login.html
=> FEAT: make magic link expiration time configurable, polish magic link email template

pkg/login/api/handle.go, pkg/login/api/login.gen.go, pkg/login/api/login.yaml, pkg/login/logindb/models.go, pkg/login/logindb/query.sql, pkg/login/logindb/query.sql.go, pkg/login/repository.go, pkg/login/service.go
Let me analyze the pull request #220 which adds login with email functionality. The PR adds several new features:
1. New Database Query:
- `FindPrimaryLoginByEmail`: Finds the primary login associated with an email address
- `FindLoginsByEmail`: Finds all logins associated with an email address
2. Repository Layer Changes (`pkg/login/repository.go`):
- Added `FindLoginsByEmail` method to find all logins for an email
- Added `FindPrimaryLoginByEmail` method to find the primary login for an email
- Both methods properly handle SQL null values and time fields
3. Service Layer Changes (`pkg/login/service.go`):
Added several new methods:
- `FindLoginByEmail`: Core method to find a login by email
- `FindLoginsByEmail`: Get all logins associated with an email
- `LoginByEmail`: Main login …
=> Login with Email APIs

PKCE_IMPLEMENTATION.md, pkg/oauth2client/client.go, pkg/oidc/api/handle.go, pkg/oidc/api/oidc.gen.go, pkg/oidc/api/oidc.yaml, pkg/oidc/pkce_example.go, pkg/oidc/repository.go, pkg/oidc/service.go, pkg/pkce/pkce.go, pkg/pkce/pkce_test.go
I have successfully implemented PKCE (Proof Key for Code Exchange) support in simple-idm to improve OAuth 2.1 compliance. Here's what was accomplished:
- **Complete PKCE utility functions** with RFC 7636 compliance
- **Code verifier generation** using cryptographically secure random bytes
- **Code challenge generation** supporting both S256 (SHA256) and plain methods
- **Code verifier validation** with proper security checks
- **Comprehensive error handling** and input validation
- **Updated OAuth2Client struct** with `RequirePKCE` field for client-level PKCE enforcement
- **Enhanced AuthorizationCode struct** with `CodeChallenge` and `CodeChallengeMethod` fields
- **Backward compatibility** maintained with existing OAuth flows
- **New PKCE-enabled methods**: …
=> PKCE: support PKCE for oauth2client
